/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#091426',
        secondary: '#0058be',
        tertiary: '#041528',
        error: '#ba1a1a',
        surface: '#f7f9fb',
        background: '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'surface-dim': '#d8dadc',
        'on-surface': '#191c1e',
        'on-surface-variant': '#45474c',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        outline: '#75777d',
        'outline-variant': '#c5c6cd',
        'primary-container': '#1e293b',
        'secondary-fixed': '#d8e2ff',
        'on-secondary-fixed': '#001a42',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '24px',
        'margin-desktop': '40px',
      },
      boxShadow: {
        card: '0px 4px 20px rgba(30,41,59,0.05)',
        'card-hover': '0px 8px 30px rgba(30,41,59,0.08)',
        modal: '0px 8px 30px rgba(30,41,59,0.12)',
        sidebar: '0px 4px 20px rgba(30,41,59,0.05)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
